grower_da_mapping = {
    "Albrecht": ["PAP", "CFV"],
    # "Aughenbaugh": ["JDOps", "PAP"],
    # "Bornitz": ["CFV", "LDB", "PAP"],
    # "Casper": ["CFV", "PAP", "FM"],
    # "Feikema": ["JDOps", "Granular"],
    # "Field": ["CFV", "PAP"],
    # "Jensen": ["CFV", "JDOps", "PAP"],
    # "Larsen": ["PAP"],
    # "Liebsch": ["FM", "JDOps", "PAP"],
    # "Malone": ["PAP", "LDB"],
    # "Murphy": ["CFV", "JDOps"],
    # "Nelson": ["CFV"],
    # "Noem": ["CFV", "JDOps", "LDB"],
    # "Odegaard": ["PAP", "LDB", "JDOps"],
    # "Olson": ["PAP", "JDOps", "CFV"],
    # "Osvog": ["PAP", "SMS"],
    # "Rieck": ["CFV"],
    # "Virchow": ["PAP", "SMS"],
    # "Wilkinson": ["JDOps", "PAP"],
}
